const STATE_KEY='opponentLineup.v2.state';
const SCOUT_KEY='opponentLineup.v2.scouting';
const EVENT_TYPES={GOAL_FOR:'GOAL_FOR',GOAL_AGAINST:'GOAL_AGAINST',YELLOW_CARD:'YELLOW_CARD',YELLOW_ACCUM_4:'YELLOW_ACCUM_4',RED_CARD:'RED_CARD',INJURY:'INJURY',LEFT_CLUB:'LEFT_CLUB',NEW_SIGNING:'NEW_SIGNING'};
const EVENT_META={
  GOAL_FOR:{label:'Goal',icon:'assets/icons/goal_for.png',minute:true,color:'#0433FF'},
  GOAL_AGAINST:{label:'Goal Against',icon:'assets/icons/goal_against.png',minute:true,color:'#FF1900'},
  YELLOW_CARD:{label:'Yellow Card',icon:'assets/icons/yellow_card.png'},
  YELLOW_ACCUM_4:{label:'4 Yellow Accumulation',icon:'assets/icons/yellow_accum_4.png'},
  RED_CARD:{label:'Red Card',icon:'assets/icons/red_card.png'},
  INJURY:{label:'Injury',icon:'assets/icons/injury.png'},
  LEFT_CLUB:{label:'Left Club',icon:'assets/icons/left_club.png'},
  NEW_SIGNING:{label:'New Signing',icon:'assets/icons/new_signing.png'}
};
// Horizontal x values are the FINAL field percentages (no extra compression).
// 2-player lines stay symmetric around 50%; 4-player lines are equally justified.
// 5-player lines use 3-up / 2-down vertical staggering to preserve full PlayerCard size.
const FORMATIONS={
 '1-4-4-2':[{label:'ST',x:37.5,y:8},{label:'ST',x:62.5,y:8},{label:'LM',x:13.5,y:34.7},{label:'CM',x:37.5,y:34.7},{label:'CM',x:62.5,y:34.7},{label:'RM',x:86.5,y:34.7},{label:'LB',x:13.5,y:61.3},{label:'CB',x:37.5,y:61.3},{label:'CB',x:62.5,y:61.3},{label:'RB',x:86.5,y:61.3},{label:'GK',x:50,y:88}],
 '1-4-3-3':[{label:'LW',x:18,y:8},{label:'ST',x:50,y:8},{label:'RW',x:82,y:8},{label:'CM',x:25,y:34.7},{label:'CM',x:50,y:34.7},{label:'CM',x:75,y:34.7},{label:'LB',x:13.5,y:61.3},{label:'CB',x:37.5,y:61.3},{label:'CB',x:62.5,y:61.3},{label:'RB',x:86.5,y:61.3},{label:'GK',x:50,y:88}],
 '1-4-2-3-1':[{label:'ST',x:50,y:8},{label:'LW',x:18,y:28},{label:'CAM',x:50,y:28},{label:'RW',x:82,y:28},{label:'CDM',x:37.5,y:48},{label:'CDM',x:62.5,y:48},{label:'LB',x:13.5,y:68},{label:'CB',x:37.5,y:68},{label:'CB',x:62.5,y:68},{label:'RB',x:86.5,y:68},{label:'GK',x:50,y:88}],
 '1-3-5-2':[{label:'ST',x:37.5,y:8},{label:'ST',x:62.5,y:8},{label:'LWB',x:13.5,y:31.2},{label:'CM',x:31.75,y:38.2},{label:'CM',x:50,y:31.2},{label:'CM',x:68.25,y:38.2},{label:'RWB',x:86.5,y:31.2},{label:'CB',x:22,y:61.3},{label:'CB',x:50,y:61.3},{label:'CB',x:78,y:61.3},{label:'GK',x:50,y:88}],
 '1-5-3-2':[{label:'ST',x:37.5,y:8},{label:'ST',x:62.5,y:8},{label:'CM',x:25,y:34.7},{label:'CM',x:50,y:34.7},{label:'CM',x:75,y:34.7},{label:'LWB',x:13.5,y:57.8},{label:'CB',x:31.75,y:64.8},{label:'CB',x:50,y:57.8},{label:'CB',x:68.25,y:64.8},{label:'RWB',x:86.5,y:57.8},{label:'GK',x:50,y:88}],
 '1-4-1-4-1':[{label:'ST',x:50,y:8},{label:'LM',x:13.5,y:28},{label:'CM',x:37.5,y:28},{label:'CM',x:62.5,y:28},{label:'RM',x:86.5,y:28},{label:'CDM',x:50,y:48},{label:'LB',x:13.5,y:68},{label:'CB',x:37.5,y:68},{label:'CB',x:62.5,y:68},{label:'RB',x:86.5,y:68},{label:'GK',x:50,y:88}],
 '1-3-4-3':[{label:'LW',x:18,y:8},{label:'ST',x:50,y:8},{label:'RW',x:82,y:8},{label:'LM',x:13.5,y:34.7},{label:'CM',x:37.5,y:34.7},{label:'CM',x:62.5,y:34.7},{label:'RM',x:86.5,y:34.7},{label:'CB',x:22,y:61.3},{label:'CB',x:50,y:61.3},{label:'CB',x:78,y:61.3},{label:'GK',x:50,y:88}],
 '1-5-4-1':[{label:'ST',x:50,y:8},{label:'LM',x:13.5,y:34.7},{label:'CM',x:37.5,y:34.7},{label:'CM',x:62.5,y:34.7},{label:'RM',x:86.5,y:34.7},{label:'LWB',x:13.5,y:57.8},{label:'CB',x:31.75,y:64.8},{label:'CB',x:50,y:57.8},{label:'CB',x:68.25,y:64.8},{label:'RWB',x:86.5,y:57.8},{label:'GK',x:50,y:88}]
};
const SUBS_GRID=[{label:'FW',x:13.5,y:8},{label:'FW',x:37.833,y:8},{label:'FW',x:62.167,y:8},{label:'FW',x:86.5,y:8},{label:'AM',x:13.5,y:28},{label:'AM',x:37.833,y:28},{label:'AM',x:62.167,y:28},{label:'AM',x:86.5,y:28},{label:'CM',x:13.5,y:48},{label:'CM',x:37.833,y:48},{label:'CM',x:62.167,y:48},{label:'CM',x:86.5,y:48},{label:'DEF',x:13.5,y:68},{label:'DEF',x:37.833,y:68},{label:'DEF',x:62.167,y:68},{label:'DEF',x:86.5,y:68},{label:'GK',x:50,y:88}];
const RESULT_CN={W:'胜',L:'负',D:'平'};
let state=null;
let ui={view:'dashboard',matchId:null,reportIndex:0};
const imageDataCache=new Map();

function uid(prefix='id'){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function cleanName(name=''){return String(name).replace(/\s*\(U21\)\s*/gi,'').trim()}
function isU21(p){return !!p?.isU21||/\(U21\)/i.test(p?.name||'')}
function playerById(id){return state.players.find(p=>p.id===id)}
function matchById(id){return state.matches.find(m=>m.id===id)}
function matchTemplate(m){return m?.kind==='SUBS'?SUBS_GRID:(FORMATIONS[m?.formation]||FORMATIONS['1-4-4-2'])}
function matchPositions(m){m.positions=m.positions||[];return m.positions}
function eventsFor(pos,type){return (pos?.events||[]).filter(e=>e.eventType===type)}
function hasEvent(pos,type){return eventsFor(pos,type).length>0}
function minuteString(arr){return `( ${arr.map(e=>String(e.minute||'').replace(/'/g,'').trim()+"'").join(',')} )`}
function saveState(){localStorage.setItem(STATE_KEY,JSON.stringify(state))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
async function loadSeed(){if(window.__SEED__)return JSON.parse(JSON.stringify(window.__SEED__));return fetch('data/seed.json').then(r=>r.json())}
async function init(){
  const stored=localStorage.getItem(STATE_KEY);
  state=stored?JSON.parse(stored):await loadSeed();
  if(!state.schemaVersion)state.schemaVersion=2;
  normalizeState();
  document.getElementById('teamName').textContent=state.team?.nameEn||state.team?.name||'';
  bindGlobal(); renderAll();
  if('serviceWorker' in navigator && location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});
}
function normalizeState(){
  state.players=state.players||[];state.matches=state.matches||[];
  state.matches.forEach(m=>{m.positions=m.positions||[];m.subGoals=m.subGoals||[];m.positions.forEach(p=>{p.events=p.events||[]})});
  if(!state.matches.some(m=>m.kind==='EXPECTED'))state.matches.push({id:uid('expected'),kind:'EXPECTED',formation:'1-4-4-2',sortOrder:10,positions:[]});
  if(!state.matches.some(m=>m.kind==='SUBS'))state.matches.push({id:uid('subs'),kind:'SUBS',formation:'SUBS-GRID',sortOrder:11,positions:[]});
  const first=state.matches.find(m=>m.kind==='MATCH');if(!ui.matchId&&first)ui.matchId=first.id;
}
function bindGlobal(){
  document.getElementById('nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)showView(b.dataset.view)});
  document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.jump)));
  document.getElementById('resetBtn').onclick=async()=>{if(confirm('Reset the local demo to the original imported data?')){state=await loadSeed();normalizeState();saveState();renderAll();toast('Demo reset')}};
  document.getElementById('backupBtn').onclick=downloadBackup;document.getElementById('jsonBtn').onclick=downloadBackup;
  document.getElementById('backupInput').onchange=importBackup;
  document.getElementById('addMatchBtn').onclick=addMatch;
  document.getElementById('addPlayerBtn').onclick=()=>openPlayerModal(null);
  document.getElementById('pptxBtn').onclick=exportPptx;
  document.getElementById('pdfBtn').onclick=()=>window.print();
  document.getElementById('scoutingImportBtn').onclick=()=>document.getElementById('scoutingFile').click();
  document.getElementById('scoutingFile').onchange=importScoutingCsv;
  window.addEventListener('resize',fitPreview);
}
function showView(v){ui.view=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`${v}View`));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.getElementById('topTitle').textContent=({dashboard:'Dashboard',squad:'Squad',matches:'Previous Matches',expected:'Expected XI',subs:'Main Subs',report:'Report',scouting:'Scouting'})[v]||v;renderView(v);setTimeout(fitPreview,0)}
function renderAll(){['dashboard','squad','matches','expected','subs','report','scouting'].forEach(renderView)}
function renderView(v){if(v==='dashboard')renderDashboard();if(v==='squad')renderSquad();if(v==='matches')renderMatchEditor();if(v==='expected')renderExpected();if(v==='subs')renderSubs();if(v==='report')renderReport();if(v==='scouting')renderScouting()}
function renderDashboard(){
 const filled=state.matches.filter(m=>m.kind==='MATCH'&&m.positions?.length);const exp=state.matches.find(m=>m.kind==='EXPECTED');const subs=state.matches.find(m=>m.kind==='SUBS');
 const eventCount=state.matches.reduce((a,m)=>a+(m.positions||[]).reduce((b,p)=>b+(p.events||[]).length,0),0);
 document.getElementById('metrics').innerHTML=`<div class="metric-card"><span>Squad</span><strong>${state.players.length}</strong><small>players</small></div><div class="metric-card"><span>Previous matches</span><strong>${filled.length}</strong><small>with lineups</small></div><div class="metric-card"><span>Expected XI</span><strong>${exp?.positions?.length||0}/11</strong><small>assigned</small></div><div class="metric-card"><span>Player events</span><strong>${eventCount}</strong><small>goals / cards / injury</small></div>`;
 document.getElementById('matchesCount').textContent=`${filled.length} saved`;
 document.getElementById('dashboardMatches').innerHTML=filled.length?filled.map(m=>`<div class="match-row"><strong>${escapeHtml(m.roundNumber||'—')}</strong><div class="opp">${escapeHtml(m.opponentName||'Opponent')}<small>${escapeHtml(m.opponentNameEn||'')}</small></div><div class="score">${m.goalsFor||0}–${m.goalsAgainst||0}</div><div class="result-pill ${m.result||'D'}">${RESULT_CN[m.result]||'平'} · ${m.result||'D'}</div></div>`).join(''):`<div class="empty-state">No completed match lineups yet.</div>`;
}
function renderSquad(){document.getElementById('squadGrid').innerHTML=state.players.map(p=>`<button class="player-tile" data-player="${p.id}"><span class="num-chip ${isU21(p)?'u21':''}">${p.squadNumber}</span><div class="photo-wrap">${p.photoAsset?`<img src="${p.photoAsset}" alt="">`:''}</div><div class="meta"><b>${escapeHtml(cleanName(p.name))}</b><small>${escapeHtml(p.nameEn||'')} · ${p.foot||'R'} · ${p.height?`${p.height}cm`:'—'}</small></div></button>`).join('');document.querySelectorAll('#squadGrid [data-player]').forEach(b=>b.onclick=()=>openPlayerModal(b.dataset.player))}
function addMatch(){const m={id:uid('match'),analysisId:state.analysis?.id,kind:'MATCH',roundNumber:'',opponentName:'',opponentNameEn:'',goalsFor:0,goalsAgainst:0,result:'D',formation:'1-4-4-2',sortOrder:Math.max(0,...state.matches.filter(x=>x.kind==='MATCH').map(x=>x.sortOrder||0))+1,positions:[],subGoals:[]};state.matches.push(m);ui.matchId=m.id;saveState();renderAll();showView('matches');toast('Match added')}
function renderMatchEditor(){const matches=state.matches.filter(m=>m.kind==='MATCH').sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0));if(!matches.length){document.getElementById('matchEditorHost').innerHTML='<div class="empty-state">Add a match to start.</div>';return}if(!matches.some(m=>m.id===ui.matchId))ui.matchId=matches[0].id;document.getElementById('matchEditorHost').innerHTML=editorHtml(matchById(ui.matchId),'match',matches);bindEditor(document.getElementById('matchEditorHost'),matchById(ui.matchId),'match')}
function renderExpected(){const m=state.matches.find(x=>x.kind==='EXPECTED');document.getElementById('expectedEditorHost').innerHTML=editorHtml(m,'expected');bindEditor(document.getElementById('expectedEditorHost'),m,'expected')}
function renderSubs(){const m=state.matches.find(x=>x.kind==='SUBS');document.getElementById('subsEditorHost').innerHTML=editorHtml(m,'subs');bindEditor(document.getElementById('subsEditorHost'),m,'subs')}
function editorX(x){return Math.max(0,Math.min(100,x??50))}
function rowMap(template){const rows=[...new Set(template.map(x=>x.y))].sort((a,b)=>a-b);const map=new Map();if(!rows.length)return map;const gk=rows.at(-1),other=rows.slice(0,-1);const top=(55/560)+.08175,bottom=(410/560)-.08175,gkOut=Math.min((540/560)-.08175-.006,(410/560)+.025+.08175);if(other.length===1)map.set(other[0],(top+bottom)/2*100);else other.forEach((r,i)=>map.set(r,(top+i/(other.length-1)*(bottom-top))*100));map.set(gk,gkOut*100);return map}
function editorHtml(m,mode,matches=[]){
 const template=matchTemplate(m),rm=rowMap(template);
 const selector=mode==='match'?`<div><label>Match</label><select id="matchSelect">${matches.map(x=>`<option value="${x.id}" ${x.id===m.id?'selected':''}>${escapeHtml(x.roundNumber||'New')} · ${escapeHtml(x.opponentName||'Opponent')}</option>`).join('')}</select></div>`:'';
 const matchFields=mode==='match'?`<div class="form-row three"><div><label>Round</label><input class="input" data-field="roundNumber" value="${escapeHtml(m.roundNumber||'')}"></div><div><label>Opponent (Chinese)</label><input class="input" data-field="opponentName" value="${escapeHtml(m.opponentName||'')}"></div><div><label>Opponent (EN)</label><input class="input" data-field="opponentNameEn" value="${escapeHtml(m.opponentNameEn||'')}"></div></div><div class="form-row three"><div><label>Goals For</label><input class="input" type="number" min="0" data-field="goalsFor" value="${m.goalsFor||0}"></div><div><label>Goals Against</label><input class="input" type="number" min="0" data-field="goalsAgainst" value="${m.goalsAgainst||0}"></div><div><label>Result</label><select data-field="result"><option value="W" ${m.result==='W'?'selected':''}>Win · 胜</option><option value="D" ${m.result==='D'?'selected':''}>Draw · 平</option><option value="L" ${m.result==='L'?'selected':''}>Loss · 负</option></select></div></div>`:'';
 const formation=mode==='subs'?`<div><label>Layout</label><input class="input" value="4 × 4 + GK" disabled></div>`:`<div><label>Formation</label><select data-field="formation">${Object.keys(FORMATIONS).map(f=>`<option ${f===m.formation?'selected':''}>${f}</option>`).join('')}</select></div>`;
 const slots=template.map((s,i)=>{const p=(m.positions||[]).find(x=>x.positionIndex===i);return `<div class="editor-slot" data-slot="${i}" style="left:${editorX(s.x)}%;top:${rm.get(s.y)??50}%">${p?miniPlayerHtml(p):`<button class="empty-slot" title="${s.label}">+</button>`}</div>`}).join('');
 return `<div class="editor-layout"><div class="pitch-editor"><div class="pitch-stage"><img class="field-img" src="assets/field_exact_4x.jpg">${slots}</div></div><div class="panel editor-controls">${selector}${matchFields}${formation}<div class="legend">${Object.values(EVENT_META).map(e=>`<span class="legend-chip"><img src="${e.icon}">${e.label}</span>`).join('')}</div><button class="btn primary" data-save>Save changes</button>${mode==='match'?'<button class="btn danger" data-delete>Delete match</button>':''}<p class="muted" style="font-size:11px;line-height:1.45">Tap an empty slot to assign a player. Tap an occupied player to edit goals, cards, injury, transfers or player details.</p></div></div>`
}
function miniPlayerHtml(pos){const p=playerById(pos.playerId);if(!p)return '<button class="empty-slot">+</button>';return `<button class="mini-player" data-occupied title="Edit ${escapeHtml(cleanName(p.name))}">${eventStacks(pos,'mini')}${p.photoAsset?`<img src="${p.photoAsset}" alt="">`:''}<div class="mini-card"><div class="r"><span class="num ${isU21(p)?'u21':''}">${p.squadNumber}</span><span class="nm">${escapeHtml(cleanName(p.name))}</span></div><div class="r"><span class="foot ${p.foot==='L'?'left':''}">${p.foot||'R'}</span><span class="ht">${p.height?`${p.height}cm`:'—'}</span></div></div></button>`}
function eventStacks(pos,kind='mini'){
 const isGk=pos?.positionLabel==='GK';
 const left=[EVENT_TYPES.NEW_SIGNING,EVENT_TYPES.LEFT_CLUB,EVENT_TYPES.INJURY,EVENT_TYPES.YELLOW_CARD,EVENT_TYPES.YELLOW_ACCUM_4,EVENT_TYPES.RED_CARD].filter(t=>hasEvent(pos,t)).map(t=>`<img src="${EVENT_META[t].icon}" alt="">`).join('');
 const gf=eventsFor(pos,EVENT_TYPES.GOAL_FOR),ga=eventsFor(pos,EVENT_TYPES.GOAL_AGAINST);
 const goals=`<div class="goal-stack ${isGk?'gk':''}">${gf.length?`<span class="goal-line for"><img src="${EVENT_META.GOAL_FOR.icon}">${minuteString(gf)}</span>`:''}${ga.length?`<span class="goal-line against"><img src="${EVENT_META.GOAL_AGAINST.icon}">${minuteString(ga)}</span>`:''}</div>`;
 return `${left?`<div class="event-stack ${isGk?'gk':''}">${left}</div>`:''}${gf.length||ga.length?goals:''}`
}
function bindEditor(host,m,mode){
 host.querySelectorAll('[data-slot]').forEach(el=>el.onclick=e=>{e.stopPropagation();openSlotModal(m.id,Number(el.dataset.slot),mode)});
 host.querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>{let val=el.value;if(el.type==='number')val=Number(val);m[el.dataset.field]=val;if(el.dataset.field==='formation'){const tpl=matchTemplate(m);m.positions=(m.positions||[]).filter(p=>p.positionIndex<tpl.length).map(p=>({...p,positionLabel:tpl[p.positionIndex]?.label||p.positionLabel}))}saveState();renderView(mode==='expected'?'expected':mode==='subs'?'subs':'matches')});
 const sel=host.querySelector('#matchSelect');if(sel)sel.onchange=()=>{ui.matchId=sel.value;renderMatchEditor()};
 const save=host.querySelector('[data-save]');if(save)save.onclick=()=>{saveState();renderAll();toast('Saved')};
 const del=host.querySelector('[data-delete]');if(del)del.onclick=()=>{if(confirm('Delete this match?')){state.matches=state.matches.filter(x=>x.id!==m.id);ui.matchId=state.matches.find(x=>x.kind==='MATCH')?.id||null;saveState();renderAll();toast('Match deleted')}}
}
function openSlotModal(matchId,index,mode){const m=matchById(matchId),tpl=matchTemplate(m),pos=(m.positions||[]).find(x=>x.positionIndex===index),currentPlayer=pos?playerById(pos.playerId):null;const selected=currentPlayer?.id||'';const goalFor=pos?eventsFor(pos,EVENT_TYPES.GOAL_FOR).map(x=>x.minute).join(', '):'';const goalAgainst=pos?eventsFor(pos,EVENT_TYPES.GOAL_AGAINST).map(x=>x.minute).join(', '):'';
 const modal=document.getElementById('modal');modal.innerHTML=`<h3>${pos?'Edit player':'Assign player'} · ${tpl[index]?.label||''}</h3><p>Select a squad member and apply the report events. Icons are the approved MD14 v0.9 set.</p><div class="picker-grid">${state.players.map(p=>`<button class="picker-item ${p.id===selected?'selected':''}" data-pick="${p.id}">${p.photoAsset?`<img src="${p.photoAsset}" alt="">`:''}<b>#${p.squadNumber} ${escapeHtml(cleanName(p.name))}</b><small>${p.foot||'R'} · ${p.height?`${p.height}cm`:'—'}</small></button>`).join('')}</div><div style="margin-top:14px" class="event-editor"><div class="event-row"><div class="head"><img src="${EVENT_META.GOAL_FOR.icon}"><b>Goal</b></div><input class="input minute" id="evGF" value="${escapeHtml(goalFor)}" placeholder="78, 90+2"></div><div class="event-row"><div class="head"><img src="${EVENT_META.GOAL_AGAINST.icon}"><b>Goal Against</b></div><input class="input minute" id="evGA" value="${escapeHtml(goalAgainst)}" placeholder="66"></div>${[EVENT_TYPES.YELLOW_CARD,EVENT_TYPES.YELLOW_ACCUM_4,EVENT_TYPES.RED_CARD,EVENT_TYPES.INJURY,EVENT_TYPES.LEFT_CLUB,EVENT_TYPES.NEW_SIGNING].map(t=>`<label class="event-row" style="display:block"><div class="head"><img src="${EVENT_META[t].icon}"><b>${EVENT_META[t].label}</b><input type="checkbox" data-toggle="${t}" ${pos&&hasEvent(pos,t)?'checked':''}></div></label>`).join('')}</div><div class="modal-actions">${pos?'<button class="btn danger" id="removeSlot">Remove</button>':''}<button class="btn" id="cancelModal">Cancel</button><button class="btn primary" id="saveSlot">Save</button></div>`;
 let picked=selected;modal.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{picked=b.dataset.pick;modal.querySelectorAll('[data-pick]').forEach(x=>x.classList.toggle('selected',x===b))});
 openModal();document.getElementById('cancelModal').onclick=closeModal;if(pos)document.getElementById('removeSlot').onclick=()=>{m.positions=m.positions.filter(x=>x.positionIndex!==index);saveState();closeModal();renderAll();renderView(mode==='expected'?'expected':mode==='subs'?'subs':'matches')};
 document.getElementById('saveSlot').onclick=()=>{if(!picked){toast('Select a player');return}m.positions=m.positions.filter(x=>x.positionIndex!==index&&x.playerId!==picked);const events=[];parseMinutes(document.getElementById('evGF').value).forEach((minute,i)=>events.push({id:uid('ev'),matchId:m.id,playerId:picked,eventType:EVENT_TYPES.GOAL_FOR,minute,sortOrder:i}));parseMinutes(document.getElementById('evGA').value).forEach((minute,i)=>events.push({id:uid('ev'),matchId:m.id,playerId:picked,eventType:EVENT_TYPES.GOAL_AGAINST,minute,sortOrder:i}));modal.querySelectorAll('[data-toggle]').forEach(ch=>{if(ch.checked)events.push({id:uid('ev'),matchId:m.id,playerId:picked,eventType:ch.dataset.toggle,minute:null,sortOrder:0})});m.positions.push({id:pos?.id||uid('pos'),matchId:m.id,playerId:picked,positionIndex:index,positionLabel:tpl[index]?.label||'',events});m.positions.sort((a,b)=>a.positionIndex-b.positionIndex);saveState();closeModal();renderAll();renderView(mode==='expected'?'expected':mode==='subs'?'subs':'matches');toast('Player saved')}
}
function parseMinutes(s){return String(s||'').split(',').map(x=>x.trim().replace(/'/g,'')).filter(Boolean)}
function openPlayerModal(id){const p=id?playerById(id):{id:uid('p'),squadNumber:'',name:'',nameEn:'',foot:'R',height:'',isU21:false,photoAsset:null};const isNew=!id;const modal=document.getElementById('modal');modal.innerHTML=`<h3>${isNew?'Add player':`#${p.squadNumber} ${escapeHtml(cleanName(p.name))}`}</h3><p>Player identity used in lineup cards and exported reports.</p><div class="form-row"><div><label>Squad number</label><input class="input" id="pNum" type="number" value="${p.squadNumber??''}"></div><div><label>Foot</label><select id="pFoot"><option value="R" ${p.foot==='R'?'selected':''}>R</option><option value="L" ${p.foot==='L'?'selected':''}>L</option><option value="BOTH" ${p.foot==='BOTH'?'selected':''}>BOTH</option></select></div></div><div style="margin-top:8px"><label>Name shown on report</label><input class="input" id="pName" value="${escapeHtml(cleanName(p.name))}"></div><div style="margin-top:8px"><label>English / pinyin name</label><input class="input" id="pNameEn" value="${escapeHtml(p.nameEn||'')}"></div><div class="form-row" style="margin-top:8px"><div><label>Height (cm)</label><input class="input" id="pHeight" type="number" value="${p.height??''}"></div><div><label>U21</label><select id="pU21"><option value="false" ${!isU21(p)?'selected':''}>No</option><option value="true" ${isU21(p)?'selected':''}>Yes</option></select></div></div><div style="margin-top:8px"><label>Player photo (optional)</label><input class="input" id="pPhoto" type="file" accept="image/*"></div><div class="modal-actions">${!isNew?'<button class="btn danger" id="deletePlayer">Delete</button>':''}<button class="btn" id="cancelModal">Cancel</button><button class="btn primary" id="savePlayer">Save</button></div>`;openModal();document.getElementById('cancelModal').onclick=closeModal;if(!isNew)document.getElementById('deletePlayer').onclick=()=>{if(confirm('Delete this player and remove them from lineups?')){state.players=state.players.filter(x=>x.id!==p.id);state.matches.forEach(m=>m.positions=(m.positions||[]).filter(x=>x.playerId!==p.id));saveState();closeModal();renderAll();toast('Player deleted')}};document.getElementById('savePlayer').onclick=async()=>{p.squadNumber=Number(document.getElementById('pNum').value)||0;p.name=document.getElementById('pName').value.trim();p.nameEn=document.getElementById('pNameEn').value.trim();p.foot=document.getElementById('pFoot').value;p.height=Number(document.getElementById('pHeight').value)||null;p.isU21=document.getElementById('pU21').value==='true';const photo=document.getElementById('pPhoto').files?.[0];if(photo)p.photoAsset=await fileToDataUri(photo);if(isNew)state.players.push(p);state.players.sort((a,b)=>(a.squadNumber||0)-(b.squadNumber||0));saveState();closeModal();renderAll();toast('Player saved')}}
function openModal(){document.getElementById('modalBackdrop').classList.remove('hidden')}
function closeModal(){document.getElementById('modalBackdrop').classList.add('hidden')}

function reportPages(){const matches=state.matches.filter(m=>m.kind==='MATCH'&&(m.positions?.length||m.roundNumber||m.opponentName)).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)).slice(-3);const e=state.matches.find(m=>m.kind==='EXPECTED'),s=state.matches.find(m=>m.kind==='SUBS');return [...matches,e,s].filter(Boolean)}
function renderReport(){const pages=reportPages();if(ui.reportIndex>=pages.length)ui.reportIndex=0;document.getElementById('reportStrip').innerHTML=pages.map((m,i)=>`<button class="report-thumb ${i===ui.reportIndex?'active':''}" data-page="${i}"><div class="tiny"><div style="font-size:5px;color:#000;padding:4px">${m.kind==='EXPECTED'?'预计首发名单':m.kind==='SUBS'?'主要替补球员':escapeHtml(m.roundNumber||'Match')}</div></div><span>${m.kind==='MATCH'?escapeHtml(m.roundNumber||'Match'):m.kind==='EXPECTED'?'Expected XI':'Main Subs'}</span></button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{ui.reportIndex=Number(b.dataset.page);renderReport()});document.getElementById('reportPreview').innerHTML=pages.length?reportPageHtml(pages[ui.reportIndex]):'<div class="empty-state">No report pages yet.</div>';const pp=document.getElementById('printPages');if(pp)pp.innerHTML=pages.map(reportPageHtml).join('');fitPreview()}
function reportPageHtml(m){const tpl=matchTemplate(m);let title='';if(m.kind==='EXPECTED')title=state.settings?.reportTitleExpected||'预计首发名单';else if(m.kind==='SUBS')title=state.settings?.reportTitleSubs||'主要替补球员';else title=`${m.roundNumber||''}_ VS ${m.opponentName||''} _ ${m.goalsFor||0}-${m.goalsAgainst||0} (${RESULT_CN[m.result]||'平'})`;
 const players=(m.positions||[]).map(pos=>{const slot=tpl[pos.positionIndex];if(!slot)return'';return reportPlayerHtml(pos,slot)}).join('');return `<div class="report-page"><img class="field-img" src="assets/field_exact_4x.jpg"><div class="report-title">${escapeHtml(title)}</div>${players}</div>`}
function reportXY(slot){return{xPct:Math.max(0,Math.min(100,slot.x??50)),yPct:15.1+.885*(slot.y??50)}}
function reportPlayerHtml(pos,slot){const p=playerById(pos.playerId);if(!p)return'';const xy=reportXY(slot);const anchorX=xy.xPct/100*540,anchorY=xy.yPct/100*720;const left=anchorX-59.9375,top=anchorY-94.369;const nm=cleanName(p.name),small=nm.length>9;const isGk=slot.label==='GK';const leftEvents=[EVENT_TYPES.NEW_SIGNING,EVENT_TYPES.LEFT_CLUB,EVENT_TYPES.INJURY,EVENT_TYPES.YELLOW_CARD,EVENT_TYPES.YELLOW_ACCUM_4,EVENT_TYPES.RED_CARD].filter(t=>hasEvent(pos,t)).map(t=>`<img src="${EVENT_META[t].icon}">`).join('');const gf=eventsFor(pos,EVENT_TYPES.GOAL_FOR),ga=eventsFor(pos,EVENT_TYPES.GOAL_AGAINST);return `<div class="report-player" style="left:${left}px;top:${top}px">${leftEvents?`<div class="report-events ${isGk?'gk':''}">${leftEvents}</div>`:''}${gf.length||ga.length?`<div class="report-goals ${isGk?'gk':''}">${gf.length?`<span class="report-goal for"><img src="${EVENT_META.GOAL_FOR.icon}">${minuteString(gf)}</span>`:''}${ga.length?`<span class="report-goal against"><img src="${EVENT_META.GOAL_AGAINST.icon}">${minuteString(ga)}</span>`:''}</div>`:''}${p.photoAsset?`<img class="head" src="${p.photoAsset}">`:''}<div class="report-card"><div class="fill-num"></div><div class="fill-name"></div><div class="fill-foot"></div><div class="fill-height"></div><div class="outer"></div><div class="vline"></div><div class="hline"></div><span class="txt txt-num ${isU21(p)?'u21':''}">${p.squadNumber}</span><span class="txt txt-name ${small?'small':''}">${escapeHtml(nm)}</span><span class="txt txt-foot ${p.foot==='L'?'left':''}">${p.foot||'R'}</span><span class="txt txt-height">${p.height?`${p.height}cm`:'—'}</span></div></div>`}
function fitPreview(){const canvas=document.querySelector('.report-canvas');const page=document.querySelector('.report-page');if(canvas&&page&&window.innerWidth<720){const scale=Math.min(1,(canvas.clientWidth-12)/540);page.style.transform=`scale(${scale})`;page.parentElement.style.height=`${720*scale}px`;page.parentElement.style.width=`${540*scale}px`}else if(page){page.style.transform='';if(page.parentElement){page.parentElement.style.height='';page.parentElement.style.width=''}}}

async function urlToDataUri(url){if(imageDataCache.has(url))return imageDataCache.get(url);const b=await fetch(url).then(r=>r.blob());const data=await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(b)});imageDataCache.set(url,data);return data}
function pt(v){return v/72}
function reportPlayerGeom(slot){const xy=reportXY(slot),anchorX=xy.xPct/100*540,anchorY=xy.yPct/100*720;return{left:anchorX-59.9375,top:anchorY-94.369}}
async function exportPptx(){const btn=document.getElementById('pptxBtn'),status=document.getElementById('exportStatus');btn.disabled=true;status.textContent='Building editable PPTX…';try{const pptx=new PptxGenJS();pptx.defineLayout({name:'LINEUP_7_5x10',width:7.5,height:10});pptx.layout='LINEUP_7_5x10';pptx.author='Opponent Lineup App';pptx.subject='Opponent lineup prediction';pptx.company='';pptx.lang='zh-CN';pptx.theme={headFontFace:'Arial',bodyFontFace:'Arial',lang:'zh-CN'};const field=await urlToDataUri('assets/field_exact_4x.jpg');for(const m of reportPages()){const slide=pptx.addSlide();slide.background={color:'FFFFFF'};slide.addImage({data:field,x:0,y:0,w:7.5,h:10});await addPptxTitle(pptx,slide,m);const tpl=matchTemplate(m);for(const pos of (m.positions||[])){const slot=tpl[pos.positionIndex];const p=playerById(pos.playerId);if(slot&&p)await addPptxPlayer(pptx,slide,p,pos,slot)}}const filename=`Lineup_${(state.team?.nameEn||state.team?.name||'Opponent').replace(/[^\w\-]+/g,'_')}_${typeof currentReportFileStem==='function'?currentReportFileStem():'Report'}_${new Date().toISOString().slice(0,10)}.pptx`;await pptx.writeFile({fileName:filename});status.textContent='PPTX exported';toast('PPTX ready for Keynote')}catch(err){console.error(err);status.textContent='Export error';toast('PPTX export failed')}finally{btn.disabled=false}}
async function addPptxTitle(pptx,slide,m){let text,w;if(m.kind==='EXPECTED'){text=state.settings?.reportTitleExpected||'预计首发名单';w=120.269}else if(m.kind==='SUBS'){text=state.settings?.reportTitleSubs||'主要替补球员';w=120.269}else{text=`${m.roundNumber||''}_ VS ${m.opponentName||''} _ ${m.goalsFor||0}-${m.goalsAgainst||0} (${RESULT_CN[m.result]||'平'})`;w=Math.max(185,Math.min(350,80+text.length*10))}slide.addText(text,{x:pt(10.843),y:pt(16.953),w:pt(w),h:pt(32.2),fontFace:'Arial',fontSize:18,color:'FFFFFF',fill:{color:'000000'},line:{color:'000000',transparency:100},margin:0.03,valign:'mid',breakLine:false,fit:'shrink'})}
async function addPptxPlayer(pptx,slide,p,pos,slot){const g=reportPlayerGeom(slot),cx=g.left,cy=g.top+76.119;const ST=pptx.ShapeType;if(p.photoAsset){const img=await urlToDataUri(p.photoAsset);slide.addImage({data:img,x:pt(g.left+22.438),y:pt(g.top),w:pt(75),h:pt(75),transparency:0})}
 const transparent={color:'FFFFFF',transparency:100};slide.addShape(ST.rect,{x:pt(cx),y:pt(cy),w:pt(30.537),h:pt(20),fill:{color:'000000'},line:{color:'000000',transparency:100}});slide.addShape(ST.rect,{x:pt(cx+30.537),y:pt(cy),w:pt(89.338),h:pt(20),fill:{color:'FFFFFF'},line:{color:'FFFFFF',transparency:100}});slide.addShape(ST.rect,{x:pt(cx),y:pt(cy+20),w:pt(30.537),h:pt(16.5),fill:{color:'FFFFFF'},line:{color:'FFFFFF',transparency:100}});slide.addShape(ST.rect,{x:pt(cx+30.537),y:pt(cy+20),w:pt(89.338),h:pt(16.5),fill:{color:'FFFFFF'},line:{color:'FFFFFF',transparency:100}});slide.addShape(ST.rect,{x:pt(cx-1),y:pt(cy-1),w:pt(121.875),h:pt(38.5),fill:transparent,line:{color:'000000',width:2}});slide.addShape(ST.line,{x:pt(cx+30.537),y:pt(cy-1),w:0,h:pt(38.5),line:{color:'000000',width:2}});slide.addShape(ST.line,{x:pt(cx-1),y:pt(cy+20),w:pt(121.875),h:0,line:{color:'000000',width:2}});
 const base={fontFace:'Arial',bold:true,margin:0,align:'center',valign:'mid',breakLine:false,fit:'shrink'};slide.addText(String(p.squadNumber??''),{...base,x:pt(cx),y:pt(cy),w:pt(30.537),h:pt(20),fontSize:15,color:isU21(p)?'00FDFF':'FFFFFF'});const nm=cleanName(p.name);slide.addText(nm,{...base,x:pt(cx+30.537),y:pt(cy),w:pt(89.338),h:pt(20),fontSize:nm.length>9?11:15,color:'000000'});slide.addText(p.foot||'R',{...base,x:pt(cx),y:pt(cy+20),w:pt(30.537),h:pt(16.5),fontSize:12,color:p.foot==='L'?'FF1900':'000000'});slide.addText(p.height?`${p.height}cm`:'',{...base,x:pt(cx+30.537),y:pt(cy+20),w:pt(89.338),h:pt(16.5),fontSize:12,color:'000000'});
 let evY=g.top+5;for(const type of [EVENT_TYPES.NEW_SIGNING,EVENT_TYPES.LEFT_CLUB,EVENT_TYPES.INJURY,EVENT_TYPES.YELLOW_CARD,EVENT_TYPES.YELLOW_ACCUM_4,EVENT_TYPES.RED_CARD])if(hasEvent(pos,type)){const data=await urlToDataUri(EVENT_META[type].icon);slide.addImage({data,x:pt(g.left-17),y:pt(evY),w:pt(20),h:pt(20)});evY+=22}
 const gf=eventsFor(pos,EVENT_TYPES.GOAL_FOR),ga=eventsFor(pos,EVENT_TYPES.GOAL_AGAINST);const isGk=slot.label==='GK';let gy=g.top+(isGk?48:10);const gx=g.left+(isGk?87:98),tx=g.left+(isGk?104:115);if(gf.length){const data=await urlToDataUri(EVENT_META.GOAL_FOR.icon);slide.addImage({data,x:pt(gx),y:pt(gy),w:pt(15),h:pt(15)});slide.addText(minuteString(gf),{x:pt(tx),y:pt(gy-1),w:pt(80),h:pt(17),fontFace:'Arial',fontSize:9,bold:true,color:'0433FF',margin:0,fill:transparent,line:{color:'FFFFFF',transparency:100},breakLine:false,fit:'shrink'});gy+=18}if(ga.length){const data=await urlToDataUri(EVENT_META.GOAL_AGAINST.icon);slide.addImage({data,x:pt(gx),y:pt(gy),w:pt(15),h:pt(15)});slide.addText(minuteString(ga),{x:pt(tx),y:pt(gy-1),w:pt(80),h:pt(17),fontFace:'Arial',fontSize:9,bold:true,color:'FF1900',margin:0,fill:transparent,line:{color:'FFFFFF',transparency:100},breakLine:false,fit:'shrink'})}}
function fileToDataUri(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(file)})}
function downloadBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});downloadBlob(blob,`Opponent_Lineup_Backup_${new Date().toISOString().slice(0,10)}.json`)}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importBackup(e){const f=e.target.files?.[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!obj.players||!obj.matches)throw new Error('Invalid backup');state=obj;normalizeState();saveState();renderAll();toast('Backup imported')}catch(err){toast('Invalid backup file')}e.target.value=''}
function importScoutingCsv(e){const f=e.target.files?.[0];if(!f)return;f.text().then(text=>{const lines=text.trim().split(/\r?\n/);const head=(lines.shift()||'').split(',').map(x=>x.trim());const rows=lines.map(line=>{const vals=line.split(',');return Object.fromEntries(head.map((h,i)=>[h,(vals[i]||'').trim()]))});localStorage.setItem(SCOUT_KEY,JSON.stringify({headers:head,rows,importedAt:new Date().toISOString()}));renderScouting();toast(`${rows.length} scouting rows imported`)}).catch(()=>toast('CSV import error'));e.target.value=''}
function renderScouting(){const d=JSON.parse(localStorage.getItem(SCOUT_KEY)||'null');const el=document.getElementById('scoutingStatus');if(el)el.textContent=d?`${d.rows.length} rows imported · ${d.headers.length} fields · ${new Date(d.importedAt).toLocaleString()}`:'No scouting dataset imported.'}

