const WORKSPACE_KEY='opponentLineup.v3.workspace';
const WORKSPACE_DB='OpponentLineupWorkspace';
const WORKSPACE_STORE='data';
const WORKSPACE_ID='main';
const LEGACY_STATE_KEYS=['opponentLineup.v2_2_1.state','opponentLineup.v2_2.state','opponentLineup.v2.state'];
let workspace=null;
let pendingSquadTeamId=null;

function cloneData(v){return JSON.parse(JSON.stringify(v));}
function valuesEqual(a,b){if(a==null&&b==null)return true;return String(a??'')===String(b??'');}
function editedFieldKeys(p){return Object.keys(p?.editedFields||{}).filter(k=>p.editedFields[k]);}
function hasManualEdits(p){return editedFieldKeys(p).length>0;}
function fieldEdited(p,key){return !!p?.editedFields?.[key];}
function importedValue(p,key){return p?.importedValues?cloneData(p.importedValues[key]):undefined;}
function fieldLabelHtml(p,key,label){return `<span class="field-label-line"><span>${label}</span>${fieldEdited(p,key)?'<span class="edited-badge">Edited by me</span>':''}${fieldEdited(p,key)&&p?.importedValues?`<button type="button" class="reset-imported" data-reset-field="${key}">Reset to imported value</button>`:''}</span>`;}
function setManualEditFlag(p,key,value){p.editedFields=p.editedFields||{};if(!p.importedValues||!(key in p.importedValues)){delete p.editedFields[key];return;}if(valuesEqual(value,p.importedValues[key]))delete p.editedFields[key];else p.editedFields[key]=true;}
function nowIso(){return new Date().toISOString();}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'});}
function fmtDateTime(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString();}
function safeFilePart(v){return String(v||'Report').trim().replace(/[^\p{L}\p{N}_\-]+/gu,'_').replace(/^_+|_+$/g,'').slice(0,60)||'Report';}
function currentReportFileStem(){return safeFilePart(activeReport()?.name||'Report');}
function defaultSettings(){return {reportTitleExpected:'预计首发名单',reportTitleSubs:'主要替补球员',uiLanguage:'en',reportCoordinateSystem:{width:540,height:720}};}
function blankMatches(){return [
  {id:uid('match'),kind:'MATCH',roundNumber:'',opponentName:'',opponentNameEn:'',goalsFor:0,goalsAgainst:0,result:'D',formation:'1-4-4-2',sortOrder:1,positions:[],subGoals:[]},
  {id:uid('expected'),kind:'EXPECTED',formation:'1-4-4-2',sortOrder:10,positions:[],subGoals:[]},
  {id:uid('subs'),kind:'SUBS',formation:'SUBS-GRID',sortOrder:11,positions:[],subGoals:[]}
];}
function normalizePlayers(players){return (players||[]).map(raw=>{const p={id:raw.id||uid('p'),squadNumber:Number(raw.squadNumber??raw.number??0)||0,name:raw.name||raw.playerName||'',nameEn:raw.nameEn||raw.pinyin||raw.englishName||'',foot:String(raw.foot||'R').toUpperCase(),height:raw.height?Number(raw.height):null,isU21:!!raw.isU21,photoAsset:raw.photoAsset||raw.photo||raw.photoUrl||null,manuallyAdded:!!raw.manuallyAdded};const base=raw.importedValues?cloneData(raw.importedValues):{squadNumber:p.squadNumber,name:p.name,nameEn:p.nameEn,foot:p.foot,height:p.height,isU21:p.isU21,photoAsset:p.photoAsset};p.importedValues=base;p.editedFields={...(raw.editedFields||{})};for(const k of Object.keys(p.editedFields))if(valuesEqual(p[k],base[k]))delete p.editedFields[k];return p;}).sort((a,b)=>(a.squadNumber||0)-(b.squadNumber||0));}
function normalizeMatches(matches){const out=cloneData(matches||[]);out.forEach(m=>{m.id=m.id||uid(m.kind?.toLowerCase()||'match');m.positions=m.positions||[];m.subGoals=m.subGoals||[];m.positions.forEach(p=>{p.events=p.events||[];});});if(!out.some(m=>m.kind==='EXPECTED'))out.push({id:uid('expected'),kind:'EXPECTED',formation:'1-4-4-2',sortOrder:10,positions:[]});if(!out.some(m=>m.kind==='SUBS'))out.push({id:uid('subs'),kind:'SUBS',formation:'SUBS-GRID',sortOrder:11,positions:[]});return out;}
function latestRoundName(matches){const ms=(matches||[]).filter(m=>m.kind==='MATCH'&&(m.roundNumber||m.opponentName));const last=ms.at(-1);return last?.roundNumber?`Report ${last.roundNumber}`:(last?.opponentName?`Report vs ${last.opponentName}`:'Imported report');}
function legacyToWorkspace(legacy){const t0=legacy?.team||{};const teamId=t0.id||uid('team');const players=normalizePlayers(legacy?.players||[]);const matches=normalizeMatches(legacy?.matches||[]);const report={id:legacy?.analysis?.id||uid('report'),name:latestRoundName(matches),status:'draft',createdAt:legacy?.analysis?.createdAt||nowIso(),updatedAt:legacy?.analysis?.updatedAt||nowIso(),playersSnapshot:cloneData(players),matches,settings:{...defaultSettings(),...(legacy?.settings||{})},analysis:cloneData(legacy?.analysis||{id:uid('analysis'),teamId})};const team={id:teamId,sourceId:t0.sourceId||'',name:t0.name||'New Team',nameEn:t0.nameEn||t0.name||'New Team',logoUrl:t0.logoUrl||'',logoAsset:t0.logoAsset||null,createdAt:t0.createdAt||nowIso(),updatedAt:t0.updatedAt||nowIso(),archived:false,masterPlayers:cloneData(players),reports:[report]};return {schemaVersion:3,createdAt:nowIso(),updatedAt:nowIso(),activeTeamId:team.id,activeReportId:report.id,teams:[team]};}
function normalizeReport(r,team){r.id=r.id||uid('report');r.name=r.name||'Report';r.status=r.status==='archived'?'archived':'draft';r.createdAt=r.createdAt||nowIso();r.updatedAt=r.updatedAt||r.createdAt;r.playersSnapshot=normalizePlayers(r.playersSnapshot||team.masterPlayers||[]);r.matches=normalizeMatches(r.matches||blankMatches());r.settings={...defaultSettings(),...(r.settings||{})};r.analysis=r.analysis||{id:uid('analysis'),teamId:team.id};return r;}
function normalizeTeam(t){t.id=t.id||uid('team');t.name=t.name||'New Team';t.nameEn=t.nameEn||t.name;t.sourceId=t.sourceId||'';t.logoUrl=t.logoUrl||'';t.createdAt=t.createdAt||nowIso();t.updatedAt=t.updatedAt||t.createdAt;t.archived=!!t.archived;t.masterPlayers=normalizePlayers(t.masterPlayers||t.players||[]);t.reports=(t.reports||[]).map(r=>normalizeReport(r,t));if(!t.reports.length)t.reports.push(newBlankReport(t,'Report 1'));return t;}
function normalizeWorkspace(w){if(!w?.teams)return legacyToWorkspace(w);w.schemaVersion=3;w.createdAt=w.createdAt||nowIso();w.updatedAt=w.updatedAt||nowIso();w.teams=(w.teams||[]).map(normalizeTeam);if(!w.teams.length){const t=createEmptyTeamObject('New Team','New Team');w.teams.push(t);}if(!w.teams.some(t=>t.id===w.activeTeamId))w.activeTeamId=w.teams[0].id;const t=w.teams.find(x=>x.id===w.activeTeamId);if(!t.reports.some(r=>r.id===w.activeReportId))w.activeReportId=t.reports[0].id;return w;}
function createEmptyTeamObject(name,nameEn){const t={id:uid('team'),sourceId:'',name:name||'New Team',nameEn:nameEn||name||'New Team',logoUrl:'',logoAsset:null,createdAt:nowIso(),updatedAt:nowIso(),archived:false,masterPlayers:[],reports:[]};t.reports.push(newBlankReport(t,'Report 1'));return t;}
function newBlankReport(team,name){return {id:uid('report'),name:name||`Report ${(team.reports?.length||0)+1}`,status:'draft',createdAt:nowIso(),updatedAt:nowIso(),playersSnapshot:cloneData(team.masterPlayers||[]),matches:blankMatches(),settings:defaultSettings(),analysis:{id:uid('analysis'),teamId:team.id}};}
function activeTeam(){return workspace?.teams?.find(t=>t.id===workspace.activeTeamId)||workspace?.teams?.[0]||null;}
function activeReport(){const t=activeTeam();return t?.reports?.find(r=>r.id===workspace.activeReportId)||t?.reports?.[0]||null;}
function bindActiveState(){const t=activeTeam();if(!t)return;let r=activeReport();if(!r){r=newBlankReport(t,'Report 1');t.reports.push(r);workspace.activeReportId=r.id;}state={schemaVersion:3,team:t,players:r.playersSnapshot,matches:r.matches,settings:r.settings,analysis:r.analysis};normalizeState();r.playersSnapshot=state.players;r.matches=state.matches;r.settings=state.settings;r.analysis=state.analysis;ui.matchId=state.matches.find(m=>m.kind==='MATCH')?.id||null;ui.reportIndex=0;refreshContextSelectors();}
function isArchivedReport(){return activeReport()?.status==='archived';}
function guardEditable(){if(isArchivedReport()){toast('Archived report is read-only. Restore it from Reports to edit.');return false;}return true;}

function openWorkspaceDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(WORKSPACE_DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(WORKSPACE_STORE))db.createObjectStore(WORKSPACE_STORE);};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function idbGetWorkspace(){try{const db=await openWorkspaceDb();return await new Promise((resolve,reject)=>{const tx=db.transaction(WORKSPACE_STORE,'readonly');const req=tx.objectStore(WORKSPACE_STORE).get(WORKSPACE_ID);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});}catch(e){console.warn('IndexedDB read failed',e);return null;}}
async function idbPutWorkspace(data){try{const db=await openWorkspaceDb();await new Promise((resolve,reject)=>{const tx=db.transaction(WORKSPACE_STORE,'readwrite');tx.objectStore(WORKSPACE_STORE).put(data,WORKSPACE_ID);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});return true;}catch(e){console.warn('IndexedDB save failed',e);return false;}}
async function loadPersistedWorkspace(){let a=null,b=null;try{a=JSON.parse(localStorage.getItem(WORKSPACE_KEY)||'null');}catch{}b=await idbGetWorkspace();if(a&&b)return String(a.updatedAt||'')>=String(b.updatedAt||'')?a:b;return a||b;}
function persistWorkspace(){workspace.updatedAt=nowIso();try{localStorage.setItem(WORKSPACE_KEY,JSON.stringify(workspace));}catch(e){console.warn('LocalStorage quota exceeded; IndexedDB remains primary',e);}idbPutWorkspace(cloneData(workspace));const el=document.getElementById('contextLine');if(el)el.dataset.saved=Date.now();}
function saveState(){const r=activeReport(),t=activeTeam();if(!r||!t)return;r.playersSnapshot=state.players;r.matches=state.matches;r.settings=state.settings;r.analysis=state.analysis;r.updatedAt=nowIso();t.updatedAt=nowIso();persistWorkspace();refreshContextSelectors(false);}

async function init(){try{let loaded=await loadPersistedWorkspace();if(!loaded){for(const k of LEGACY_STATE_KEYS){try{const raw=localStorage.getItem(k);if(raw){loaded=JSON.parse(raw);break;}}catch{}}}if(!loaded)loaded=await loadSeed();workspace=normalizeWorkspace(loaded?.teams?loaded:legacyToWorkspace(loaded));bindActiveState();bindGlobal();renderAll();refreshContextSelectors();if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});}catch(err){console.error(err);document.body.innerHTML=`<div style="padding:30px;color:white;font-family:system-ui"><h2>App initialization failed</h2><p>${escapeHtml(err.message)}</p></div>`;}}

function refreshContextSelectors(renderLabels=true){const ts=document.getElementById('teamSelect'),rs=document.getElementById('reportSelect');const t=activeTeam(),r=activeReport();if(ts){ts.innerHTML=workspace.teams.slice().sort((a,b)=>Number(a.archived)-Number(b.archived)||String(a.nameEn).localeCompare(String(b.nameEn))).map(x=>`<option value="${x.id}" ${x.id===workspace.activeTeamId?'selected':''}>${x.archived?'[Archived] ':''}${escapeHtml(x.nameEn||x.name)}</option>`).join('');}if(rs&&t){rs.innerHTML=t.reports.slice().sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).map(x=>`<option value="${x.id}" ${x.id===workspace.activeReportId?'selected':''}>${x.status==='archived'?'[Archived] ':''}${escapeHtml(x.name)}</option>`).join('');}const status=document.getElementById('reportStatus');if(status&&r){status.textContent=r.status==='archived'?'Archived':'Draft';status.className=`context-status ${r.status}`;}const line=document.getElementById('contextLine');if(line&&t&&r)line.textContent=`${t.nameEn||t.name} · ${r.name} · autosaved locally`;if(renderLabels){const tn=document.getElementById('teamName');if(tn)tn.textContent=t?.nameEn||t?.name||'';}}
function switchTeam(teamId){const t=workspace.teams.find(x=>x.id===teamId);if(!t)return;workspace.activeTeamId=t.id;workspace.activeReportId=t.reports.slice().sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))[0]?.id||t.reports[0]?.id;bindActiveState();persistWorkspace();renderAll();showView(ui.view==='teams'?'teams':'dashboard');toast(`Loaded ${t.nameEn||t.name}`);}
function switchReport(reportId){const t=activeTeam();if(!t?.reports.some(r=>r.id===reportId))return;workspace.activeReportId=reportId;bindActiveState();persistWorkspace();renderAll();showView(ui.view==='reports'?'reports':'dashboard');toast(`Opened ${activeReport().name}`);}

function bindGlobal(){document.getElementById('nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)showView(b.dataset.view);});document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.jump)));document.getElementById('teamSelect').onchange=e=>switchTeam(e.target.value);document.getElementById('reportSelect').onchange=e=>switchReport(e.target.value);document.getElementById('quickNewReportBtn').onclick=()=>createReportForTeam(activeTeam()?.id);document.getElementById('backupBtn').onclick=downloadBackup;document.getElementById('jsonBtn').onclick=downloadReportJson;document.getElementById('backupInput').onchange=importBackup;document.getElementById('addMatchBtn').onclick=()=>{if(guardEditable())addMatch();};document.getElementById('addPlayerBtn').onclick=()=>{if(guardEditable())openPlayerModal(null);};document.getElementById('pptxBtn').onclick=exportPptx;document.getElementById('pdfBtn').onclick=()=>window.print();document.getElementById('scoutingImportBtn').onclick=()=>document.getElementById('scoutingFile').click();document.getElementById('scoutingFile').onchange=importScoutingCsv;document.getElementById('addTeamBtn').onclick=()=>openTeamModal();document.getElementById('importTeamBtn').onclick=()=>document.getElementById('teamImportInput').click();document.getElementById('teamImportInput').onchange=importTeamFile;document.getElementById('squadImportInput').onchange=importSquadFile;document.getElementById('newReportBtn').onclick=()=>createReportForTeam(activeTeam()?.id);document.getElementById('duplicateCurrentReportBtn').onclick=()=>duplicateReport(activeReport()?.id);window.addEventListener('resize',fitPreview);}
function showView(v){ui.view=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`${v}View`));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.getElementById('topTitle').textContent=({dashboard:'Dashboard',teams:'Teams',reports:'Report Archive',squad:'Squad',matches:'Previous Matches',expected:'Expected XI',subs:'Main Subs',report:'Report',scouting:'Scouting'})[v]||v;renderView(v);setTimeout(fitPreview,0);}
function renderAll(){['dashboard','teams','reports','squad','matches','expected','subs','report','scouting'].forEach(renderView);refreshContextSelectors();}
function renderView(v){if(v==='dashboard')renderDashboard();if(v==='teams')renderTeams();if(v==='reports')renderReports();if(v==='squad')renderSquad();if(v==='matches')renderMatchEditor();if(v==='expected')renderExpected();if(v==='subs')renderSubs();if(v==='report')renderReport();if(v==='scouting')renderScouting();}

const _baseRenderDashboard=renderDashboard;
renderDashboard=function(){_baseRenderDashboard();const metrics=document.getElementById('metrics'),t=activeTeam(),r=activeReport();if(metrics&&t&&r){metrics.innerHTML=`<div class="metric-card"><span>Team squad</span><strong>${t.masterPlayers.length}</strong><small>current players</small></div><div class="metric-card"><span>Saved reports</span><strong>${t.reports.length}</strong><small>${t.reports.filter(x=>x.status==='archived').length} archived</small></div>`+metrics.innerHTML;}const q=document.querySelector('#dashboardView .quick-grid');if(q&&!q.querySelector('[data-jump="teams"]'))q.insertAdjacentHTML('afterbegin',`<button class="quick" data-jump="teams"><b>Teams</b><span>Load or create opponent teams.</span></button><button class="quick" data-jump="reports"><b>Report archive</b><span>Open saved lineups and snapshots.</span></button>`);document.querySelectorAll('#dashboardView [data-jump]').forEach(b=>b.onclick=()=>showView(b.dataset.jump));};

function teamCard(t){const latest=t.reports.slice().sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))[0];const initials=(t.nameEn||t.name||'T').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();return `<article class="team-card ${t.archived?'archived':''}" data-team-card="${t.id}"><div class="team-card-head"><div class="team-avatar">${t.logoAsset||t.logoUrl?`<img src="${escapeHtml(t.logoAsset||t.logoUrl)}" alt="">`:escapeHtml(initials)}</div><div><h3>${escapeHtml(t.nameEn||t.name)}</h3><p>${escapeHtml(t.name||'')} ${t.sourceId?`· ID ${escapeHtml(t.sourceId)}`:''}</p></div><span class="archive-badge ${t.archived?'on':''}">${t.archived?'Archived':'Active'}</span></div><div class="team-stats"><span><b>${t.masterPlayers.length}</b> players</span><span><b>${t.reports.length}</b> reports</span><span>Updated ${fmtDate(t.updatedAt)}</span></div><div class="team-card-actions"><button class="btn small primary" data-team-action="open">Open</button><button class="btn small" data-team-action="new-report">New report</button><button class="btn small" data-team-action="squad-import">Import squad</button><button class="btn small ghost" data-team-action="edit">Edit</button><button class="btn small ghost" data-team-action="export">Export</button><button class="btn small ghost" data-team-action="duplicate">Duplicate</button><button class="btn small ghost" data-team-action="archive">${t.archived?'Restore':'Archive'}</button><button class="btn small danger" data-team-action="delete">Delete</button></div>${latest?`<div class="team-latest">Latest: <b>${escapeHtml(latest.name)}</b> · ${fmtDateTime(latest.updatedAt)}</div>`:''}</article>`;}
function renderTeams(){const grid=document.getElementById('teamGrid'),summary=document.getElementById('teamSummary');if(!grid)return;const active=workspace.teams.filter(t=>!t.archived).length,arch=workspace.teams.length-active;if(summary)summary.innerHTML=`<b>${workspace.teams.length} teams</b><span>${active} active · ${arch} archived · stored offline in this device</span>`;grid.innerHTML=workspace.teams.slice().sort((a,b)=>Number(a.archived)-Number(b.archived)||String(b.updatedAt).localeCompare(String(a.updatedAt))).map(teamCard).join('');grid.querySelectorAll('[data-team-card]').forEach(card=>card.onclick=e=>{const btn=e.target.closest('[data-team-action]');if(!btn)return;const id=card.dataset.teamCard,action=btn.dataset.teamAction;if(action==='open')switchTeam(id);if(action==='new-report')createReportForTeam(id);if(action==='squad-import'){pendingSquadTeamId=id;document.getElementById('squadImportInput').click();}if(action==='edit')openTeamModal(id);if(action==='export')exportTeam(id);if(action==='duplicate')duplicateTeam(id);if(action==='archive')toggleTeamArchive(id);if(action==='delete')deleteTeam(id);});}
function openTeamModal(teamId=null){const existing=teamId?workspace.teams.find(t=>t.id===teamId):null;const t=existing||{name:'',nameEn:'',sourceId:'',logoUrl:'',logoAsset:null};const modal=document.getElementById('modal');modal.innerHTML=`<h3>${existing?'Edit team':'Add team'}</h3><p>Teams keep an independent squad and full report archive.</p><div class="form-row"><div><label>Team name (Chinese / local)</label><input class="input" id="tmName" value="${escapeHtml(t.name||'')}"></div><div><label>Team name (English)</label><input class="input" id="tmNameEn" value="${escapeHtml(t.nameEn||'')}"></div></div><div class="form-row" style="margin-top:8px"><div><label>Source / Dongqiudi ID (optional)</label><input class="input" id="tmSource" value="${escapeHtml(t.sourceId||'')}"></div><div><label>Logo URL (optional)</label><input class="input" id="tmLogoUrl" value="${escapeHtml(t.logoUrl||'')}"></div></div><div style="margin-top:8px"><label>Logo image (optional)</label><input class="input" type="file" accept="image/*" id="tmLogoFile"></div><div class="modal-actions"><button class="btn" id="cancelModal">Cancel</button><button class="btn primary" id="saveTeam">${existing?'Save team':'Create team'}</button></div>`;openModal();document.getElementById('cancelModal').onclick=closeModal;document.getElementById('saveTeam').onclick=async()=>{const name=document.getElementById('tmName').value.trim(),nameEn=document.getElementById('tmNameEn').value.trim();if(!name&&!nameEn){toast('Enter a team name');return;}if(existing){existing.name=name||nameEn;existing.nameEn=nameEn||name;existing.sourceId=document.getElementById('tmSource').value.trim();existing.logoUrl=document.getElementById('tmLogoUrl').value.trim();const f=document.getElementById('tmLogoFile').files?.[0];if(f)existing.logoAsset=await fileToDataUri(f);existing.updatedAt=nowIso();}else{const nt=createEmptyTeamObject(name||nameEn,nameEn||name);nt.sourceId=document.getElementById('tmSource').value.trim();nt.logoUrl=document.getElementById('tmLogoUrl').value.trim();const f=document.getElementById('tmLogoFile').files?.[0];if(f)nt.logoAsset=await fileToDataUri(f);workspace.teams.push(nt);workspace.activeTeamId=nt.id;workspace.activeReportId=nt.reports[0].id;bindActiveState();}persistWorkspace();closeModal();renderAll();showView('teams');toast(existing?'Team saved':'Team created');};}
function duplicateTeam(id){const src=workspace.teams.find(t=>t.id===id);if(!src)return;const copy=cloneData(src);copy.id=uid('team');copy.nameEn=`${src.nameEn||src.name} Copy`;copy.name=`${src.name||src.nameEn} Copy`;copy.createdAt=nowIso();copy.updatedAt=nowIso();copy.archived=false;copy.reports.forEach((r,i)=>{r.id=uid('report');r.name=`${r.name} Copy`;r.createdAt=nowIso();r.updatedAt=nowIso();r.status='draft';r.analysis={...(r.analysis||{}),id:uid('analysis'),teamId:copy.id};});workspace.teams.push(normalizeTeam(copy));persistWorkspace();renderTeams();refreshContextSelectors();toast('Team duplicated');}
function toggleTeamArchive(id){const t=workspace.teams.find(x=>x.id===id);if(!t)return;t.archived=!t.archived;t.updatedAt=nowIso();persistWorkspace();renderTeams();refreshContextSelectors();toast(t.archived?'Team archived':'Team restored');}
function deleteTeam(id){const t=workspace.teams.find(x=>x.id===id);if(!t)return;if(!confirm(`Delete ${t.nameEn||t.name} and all ${t.reports.length} reports? This cannot be undone.`))return;if(workspace.teams.length===1){toast('Keep at least one team');return;}workspace.teams=workspace.teams.filter(x=>x.id!==id);if(workspace.activeTeamId===id){workspace.activeTeamId=workspace.teams[0].id;workspace.activeReportId=workspace.teams[0].reports[0].id;bindActiveState();}persistWorkspace();renderAll();toast('Team deleted');}
function exportTeam(id){const t=workspace.teams.find(x=>x.id===id);if(!t)return;downloadBlob(new Blob([JSON.stringify({type:'opponent-lineup-team',schemaVersion:3,exportedAt:nowIso(),team:t},null,2)],{type:'application/json'}),`${safeFilePart(t.nameEn||t.name)}_Team_Backup.json`);}
async function importTeamFile(e){const f=e.target.files?.[0];if(!f)return;try{const obj=JSON.parse(await f.text());let teams=[];if(obj.type==='opponent-lineup-team'&&obj.team)teams=[obj.team];else if(obj.teams)teams=obj.teams;else if(obj.team&&obj.players&&obj.matches)teams=legacyToWorkspace(obj).teams;else if(obj.id&&obj.reports)teams=[obj];else throw new Error('Unsupported team file');for(const raw of teams){const t=normalizeTeam(cloneData(raw));t.id=uid('team');t.createdAt=nowIso();t.updatedAt=nowIso();t.reports.forEach(r=>{r.id=uid('report');r.analysis={...(r.analysis||{}),id:uid('analysis'),teamId:t.id};});workspace.teams.push(t);}persistWorkspace();renderAll();toast(`${teams.length} team${teams.length===1?'':'s'} imported`);}catch(err){console.error(err);toast('Invalid team backup');}e.target.value='';}
function parseCsvLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++;}else q=!q;}else if(ch===','&&!q){out.push(cur);cur='';}else cur+=ch;}out.push(cur);return out;}
async function importSquadFile(e){const f=e.target.files?.[0],team=workspace.teams.find(t=>t.id===pendingSquadTeamId);if(!f||!team){e.target.value='';return;}try{let players=[];if(f.name.toLowerCase().endsWith('.json')){const o=JSON.parse(await f.text());players=normalizePlayers(Array.isArray(o)?o:(o.players||o.masterPlayers||[]));}else{const lines=(await f.text()).split(/\r?\n/).filter(x=>x.trim());const headers=parseCsvLine(lines.shift()||'').map(x=>x.trim());players=normalizePlayers(lines.map(line=>{const vals=parseCsvLine(line);return Object.fromEntries(headers.map((h,i)=>[h,vals[i]??'']));}));}if(!players.length)throw new Error('No players');team.masterPlayers=players;team.updatedAt=nowIso();if(team.id===activeTeam()?.id&&confirm(`Imported ${players.length} players. Apply this squad to the current report too?`)){const r=activeReport();r.playersSnapshot=cloneData(players);bindActiveState();}persistWorkspace();renderAll();toast(`${players.length} players imported`);}catch(err){console.error(err);toast('Squad import failed');}pendingSquadTeamId=null;e.target.value='';}

function reportCard(r){const matchCount=r.matches.filter(m=>m.kind==='MATCH'&&(m.positions?.length||m.roundNumber||m.opponentName)).length;const exp=r.matches.find(m=>m.kind==='EXPECTED');return `<article class="archive-row ${r.id===workspace.activeReportId?'current':''} ${r.status}"><div class="archive-main"><div><div class="archive-title"><h3>${escapeHtml(r.name)}</h3><span class="archive-badge ${r.status==='archived'?'on':''}">${r.status==='archived'?'Archived':'Draft'}</span>${r.id===workspace.activeReportId?'<span class="current-badge">Open</span>':''}</div><p>${matchCount} previous matches · Expected XI ${exp?.positions?.length||0}/11 · ${r.playersSnapshot.length} player snapshot</p></div><div class="archive-dates"><span>Created ${fmtDate(r.createdAt)}</span><span>Updated ${fmtDateTime(r.updatedAt)}</span></div></div><div class="archive-actions" data-report-id="${r.id}"><button class="btn small primary" data-report-action="open">Open</button><button class="btn small" data-report-action="duplicate">Duplicate</button><button class="btn small ghost" data-report-action="rename">Rename</button><button class="btn small ghost" data-report-action="archive">${r.status==='archived'?'Restore':'Archive'}</button><button class="btn small ghost" data-report-action="export">Export JSON</button><button class="btn small danger" data-report-action="delete">Delete</button></div></article>`;}
function renderReports(){const t=activeTeam(),list=document.getElementById('reportArchiveList'),summary=document.getElementById('reportArchiveSummary');if(!t||!list)return;const archived=t.reports.filter(r=>r.status==='archived').length;if(summary)summary.innerHTML=`<b>${escapeHtml(t.nameEn||t.name)}</b><span>${t.reports.length} reports · ${archived} archived · each report has an independent lineup + player snapshot</span>`;list.innerHTML=t.reports.slice().sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).map(reportCard).join('');list.querySelectorAll('[data-report-id]').forEach(row=>row.onclick=e=>{const b=e.target.closest('[data-report-action]');if(!b)return;const id=row.dataset.reportId,a=b.dataset.reportAction;if(a==='open')switchReport(id);if(a==='duplicate')duplicateReport(id);if(a==='rename')renameReport(id);if(a==='archive')toggleReportArchive(id);if(a==='export')exportReportJson(id);if(a==='delete')deleteReport(id);});}
function createReportForTeam(teamId){const t=workspace.teams.find(x=>x.id===teamId);if(!t)return;const modal=document.getElementById('modal');const n=t.reports.length+1;modal.innerHTML=`<h3>New report</h3><p>Create a fresh report for ${escapeHtml(t.nameEn||t.name)}. The current team squad is copied into a new independent snapshot.</p><div><label>Report name</label><input class="input" id="newReportName" value="Report ${n} · ${new Date().toISOString().slice(0,10)}"></div><div class="modal-actions"><button class="btn" id="cancelModal">Cancel</button><button class="btn primary" id="createReport">Create & open</button></div>`;openModal();document.getElementById('cancelModal').onclick=closeModal;document.getElementById('createReport').onclick=()=>{const r=newBlankReport(t,document.getElementById('newReportName').value.trim()||`Report ${n}`);t.reports.push(r);t.updatedAt=nowIso();workspace.activeTeamId=t.id;workspace.activeReportId=r.id;bindActiveState();persistWorkspace();closeModal();renderAll();showView('dashboard');toast('New report created');};}
function duplicateReport(id){const t=activeTeam(),src=t?.reports.find(r=>r.id===id);if(!src)return;const c=cloneData(src);c.id=uid('report');c.name=`${src.name} Copy`;c.status='draft';c.createdAt=nowIso();c.updatedAt=nowIso();c.analysis={...(c.analysis||{}),id:uid('analysis'),teamId:t.id};t.reports.push(normalizeReport(c,t));workspace.activeReportId=c.id;bindActiveState();persistWorkspace();renderAll();showView('reports');toast('Report duplicated');}
function renameReport(id){const r=activeTeam()?.reports.find(x=>x.id===id);if(!r)return;const name=prompt('Report name',r.name);if(name?.trim()){r.name=name.trim();r.updatedAt=nowIso();persistWorkspace();renderReports();refreshContextSelectors();}}
function toggleReportArchive(id){const r=activeTeam()?.reports.find(x=>x.id===id);if(!r)return;r.status=r.status==='archived'?'draft':'archived';r.updatedAt=nowIso();persistWorkspace();renderAll();toast(r.status==='archived'?'Report archived · read-only':'Report restored for editing');}
function deleteReport(id){const t=activeTeam(),r=t?.reports.find(x=>x.id===id);if(!r)return;if(t.reports.length===1){toast('Keep at least one report for this team');return;}if(!confirm(`Delete report “${r.name}”? This cannot be undone.`))return;t.reports=t.reports.filter(x=>x.id!==id);if(workspace.activeReportId===id){workspace.activeReportId=t.reports[0].id;bindActiveState();}persistWorkspace();renderAll();toast('Report deleted');}
function exportReportJson(id){const t=activeTeam(),r=t?.reports.find(x=>x.id===id);if(!t||!r)return;downloadBlob(new Blob([JSON.stringify({type:'opponent-lineup-report',schemaVersion:3,exportedAt:nowIso(),team:{id:t.id,name:t.name,nameEn:t.nameEn,sourceId:t.sourceId},report:r},null,2)],{type:'application/json'}),`${safeFilePart(t.nameEn||t.name)}_${safeFilePart(r.name)}.json`);}
function downloadReportJson(){exportReportJson(activeReport()?.id);}


const _baseRenderSquad=renderSquad;
renderSquad=function(){const grid=document.getElementById('squadGrid');if(!grid)return;grid.innerHTML=state.players.map(p=>`<button class="player-tile ${hasManualEdits(p)?'has-edits':''}" data-player="${p.id}"><span class="num-chip ${isU21(p)?'u21':''}">${p.squadNumber}</span>${hasManualEdits(p)?`<span class="player-edit-badge" title="${editedFieldKeys(p).map(k=>k).join(', ')}">Edited by me</span>`:''}<div class="photo-wrap">${p.photoAsset?`<img src="${p.photoAsset}" alt="">`:''}</div><div class="meta"><b>${escapeHtml(cleanName(p.name))}</b><small>${escapeHtml(p.nameEn||'')} · ${p.foot||'R'} · ${p.height?`${p.height}cm`:'—'}</small>${hasManualEdits(p)?`<em>${editedFieldKeys(p).length} manual ${editedFieldKeys(p).length===1?'edit':'edits'}</em>`:''}</div></button>`).join('');grid.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>openPlayerModal(b.dataset.player));};

const _baseBindEditor=bindEditor;
bindEditor=function(host,m,mode){_baseBindEditor(host,m,mode);if(isArchivedReport()){host.querySelectorAll('[data-field],[data-save],[data-delete]').forEach(el=>{el.disabled=true;el.title='Archived report is read-only';});host.classList.add('read-only-editor');}};
const _baseOpenSlotModal=openSlotModal;
openSlotModal=function(matchId,index,mode){if(!guardEditable())return;return _baseOpenSlotModal(matchId,index,mode);};
const _baseAddMatch=addMatch;
addMatch=function(){if(!guardEditable())return;return _baseAddMatch();};

openPlayerModal=function(id){
 if(!guardEditable())return;
 const p=id?playerById(id):{id:uid('p'),squadNumber:'',name:'',nameEn:'',foot:'R',height:'',isU21:false,photoAsset:null,importedValues:null,editedFields:{},manuallyAdded:true};
 const isNew=!id;
 p.editedFields=p.editedFields||{};
 if(!isNew&&!p.importedValues)p.importedValues={squadNumber:p.squadNumber,name:p.name,nameEn:p.nameEn,foot:p.foot,height:p.height,isU21:p.isU21,photoAsset:p.photoAsset};
 const modal=document.getElementById('modal');
 const statusLine=isNew?'<span class="manual-origin-badge">Added manually</span>':(hasManualEdits(p)?`<span class="manual-origin-badge">${editedFieldKeys(p).length} field${editedFieldKeys(p).length===1?'':'s'} edited by me</span>`:'<span class="imported-origin-badge">Imported data · no manual edits</span>');
 modal.innerHTML=`<h3>${isNew?'Add player':`#${p.squadNumber} ${escapeHtml(cleanName(p.name))}`}</h3>
 <p>Changes update the current team squad and this report snapshot. Older reports remain unchanged.</p>
 <div class="player-origin-row">${statusLine}</div>
 <div class="form-row">
   <div><label>${fieldLabelHtml(p,'squadNumber','Squad number')}</label><input class="input" id="pNum" type="number" value="${p.squadNumber??''}"></div>
   <div><label>${fieldLabelHtml(p,'foot','Foot')}</label><select id="pFoot"><option value="R" ${p.foot==='R'?'selected':''}>R</option><option value="L" ${p.foot==='L'?'selected':''}>L</option><option value="BOTH" ${p.foot==='BOTH'?'selected':''}>BOTH</option></select></div>
 </div>
 <div style="margin-top:8px"><label>${fieldLabelHtml(p,'name','Name shown on report')}</label><input class="input" id="pName" value="${escapeHtml(cleanName(p.name))}"></div>
 <div style="margin-top:8px"><label>${fieldLabelHtml(p,'nameEn','English / pinyin name')}</label><input class="input" id="pNameEn" value="${escapeHtml(p.nameEn||'')}"></div>
 <div class="form-row" style="margin-top:8px">
   <div><label>${fieldLabelHtml(p,'height','Height (cm)')}</label><input class="input" id="pHeight" type="number" value="${p.height??''}"></div>
   <div><label>${fieldLabelHtml(p,'isU21','U21')}</label><select id="pU21"><option value="false" ${!isU21(p)?'selected':''}>No</option><option value="true" ${isU21(p)?'selected':''}>Yes</option></select></div>
 </div>
 <div style="margin-top:8px"><label>${fieldLabelHtml(p,'photoAsset','Player photo')}</label><input class="input" id="pPhoto" type="file" accept="image/*">${p.photoAsset?'<small class="current-photo-note">Current photo kept unless you select a new one.</small>':''}</div>
 <div class="modal-actions">${!isNew?'<button class="btn danger" id="deletePlayer">Delete</button>':''}<button class="btn" id="cancelModal">Cancel</button><button class="btn primary" id="savePlayer">Save</button></div>`;
 openModal();
 document.getElementById('cancelModal').onclick=closeModal;

 modal.querySelectorAll('[data-reset-field]').forEach(btn=>btn.onclick=e=>{
   e.preventDefault();e.stopPropagation();
   const key=btn.dataset.resetField,val=importedValue(p,key);
   if(key==='squadNumber')document.getElementById('pNum').value=val??'';
   if(key==='foot')document.getElementById('pFoot').value=val||'R';
   if(key==='name')document.getElementById('pName').value=val??'';
   if(key==='nameEn')document.getElementById('pNameEn').value=val??'';
   if(key==='height')document.getElementById('pHeight').value=val??'';
   if(key==='isU21')document.getElementById('pU21').value=String(!!val);
   if(key==='photoAsset'){modal.dataset.resetPhoto='true';const note=modal.querySelector('.current-photo-note');if(note)note.textContent='Imported photo will be restored when you press Save.';}
   toast('Imported value restored · press Save');
 });

 if(!isNew)document.getElementById('deletePlayer').onclick=()=>{
   if(confirm('Delete this player from the current squad and current report? Older reports keep their snapshot.')){
     state.players=state.players.filter(x=>x.id!==p.id);
     state.matches.forEach(m=>m.positions=(m.positions||[]).filter(x=>x.playerId!==p.id));
     const t=activeTeam();t.masterPlayers=t.masterPlayers.filter(x=>x.id!==p.id);
     activeReport().playersSnapshot=state.players;saveState();closeModal();renderAll();toast('Player deleted');
   }
 };

 document.getElementById('savePlayer').onclick=async()=>{
   const next={
     squadNumber:Number(document.getElementById('pNum').value)||0,
     name:document.getElementById('pName').value.trim(),
     nameEn:document.getElementById('pNameEn').value.trim(),
     foot:document.getElementById('pFoot').value,
     height:Number(document.getElementById('pHeight').value)||null,
     isU21:document.getElementById('pU21').value==='true'
   };
   const photo=document.getElementById('pPhoto').files?.[0];
   let nextPhoto=modal.dataset.resetPhoto==='true'?importedValue(p,'photoAsset'):p.photoAsset;
   if(photo)nextPhoto=await fileToDataUri(photo);

   if(isNew){
     Object.assign(p,next,{photoAsset:nextPhoto,manuallyAdded:true,importedValues:null,editedFields:{}});
     state.players.push(p);
   }else{
     Object.assign(p,next,{photoAsset:nextPhoto});
     ['squadNumber','name','nameEn','foot','height','isU21'].forEach(k=>setManualEditFlag(p,k,p[k]));
     setManualEditFlag(p,'photoAsset',p.photoAsset);
   }

   state.players.sort((a,b)=>(a.squadNumber||0)-(b.squadNumber||0));
   const t=activeTeam(),idx=t.masterPlayers.findIndex(x=>x.id===p.id);
   if(idx>=0)t.masterPlayers[idx]=cloneData(p);else t.masterPlayers.push(cloneData(p));
   t.masterPlayers.sort((a,b)=>(a.squadNumber||0)-(b.squadNumber||0));
   activeReport().playersSnapshot=state.players;
   saveState();closeModal();renderAll();
   toast(isNew?'Player added':(hasManualEdits(p)?'Player saved · manual edits marked':'Player saved · matches imported data'));
 };
};
function downloadBackup(){downloadBlob(new Blob([JSON.stringify({type:'opponent-lineup-workspace',schemaVersion:3,exportedAt:nowIso(),...workspace},null,2)],{type:'application/json'}),`Opponent_Lineup_All_Data_${new Date().toISOString().slice(0,10)}.json`);}
async function importBackup(e){const f=e.target.files?.[0];if(!f)return;try{const obj=JSON.parse(await f.text());let w;if(obj.teams)w=obj;else if(obj.team&&obj.players&&obj.matches)w=legacyToWorkspace(obj);else throw new Error('Invalid workspace');if(!confirm('Replace all local teams and reports with this backup?')){e.target.value='';return;}workspace=normalizeWorkspace(w);bindActiveState();persistWorkspace();renderAll();showView('dashboard');toast('All data imported');}catch(err){console.error(err);toast('Invalid workspace backup');}e.target.value='';}
function importScoutingCsv(e){const f=e.target.files?.[0];if(!f)return;f.text().then(text=>{const lines=text.trim().split(/\r?\n/);const head=(lines.shift()||'').split(',').map(x=>x.trim());const rows=lines.map(line=>{const vals=line.split(',');return Object.fromEntries(head.map((h,i)=>[h,(vals[i]||'').trim()]));});const t=activeTeam();t.scouting={headers:head,rows,importedAt:nowIso()};persistWorkspace();renderScouting();toast(`${rows.length} scouting rows imported for ${t.nameEn||t.name}`);}).catch(()=>toast('CSV import error'));e.target.value='';}
function renderScouting(){const d=activeTeam()?.scouting;const el=document.getElementById('scoutingStatus');if(el)el.textContent=d?`${d.rows.length} rows imported · ${d.headers.length} fields · ${fmtDateTime(d.importedAt)} · ${activeTeam().nameEn||activeTeam().name}`:'No scouting dataset imported for this team.';}

init();
